# database.yml for product
spring:
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://${HJKIM_ERP_HOST:127.0.0.1}:${HJKIM_ERP_PORT:5432}/${HJKIM_ERP_DBNAME:erp}
      username: ${HJKIM_ERP_USERNAME:postgres}
      password: ${HJKIM_ERP_PASSWORD:1234}
      maximum-pool-size: 3
      auto-commit: false
      schema: public
      pool-name: db1